
package main.webapp.services;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HotelService", targetNamespace = "http://services.webapp.main/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HotelService {


    /**
     * 
     * @return
     *     returns java.util.List<main.webapp.services.Room>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRooms", targetNamespace = "http://services.webapp.main/", className = "main.webapp.services.GetRooms")
    @ResponseWrapper(localName = "getRoomsResponse", targetNamespace = "http://services.webapp.main/", className = "main.webapp.services.GetRoomsResponse")
    @Action(input = "http://services.webapp.main/HotelService/getRoomsRequest", output = "http://services.webapp.main/HotelService/getRoomsResponse")
    public List<Room> getRooms();

}
